### ISSUE TITLE
Error termcolor

### ISSUE THREAD

**Issue by lgcambero** [maldevel/IPGeoLocation#17]
Kali 2016.1 Rolling Release, full update && upgrade && dist-upgrade
![sin titulo](https://cloud.githubusercontent.com/assets/11602705/15021500/97eb20d8-11fd-11e6-83cc-83762aaf1328.jpg)

**Comment by maldevel** [comment]
* Python 3
* pip install termcolor
or
* pip3 install termcolor

**Comment by lgcambero** [comment]
Thank you for responding, but if you verify the catch that I sent and I have installed termcolor, but when I run ipgeolocation.py tells me not find the module. Any other ideas? Thank you.

**Comment by maldevel** [comment]
Hello, kali has python 2.x installed by default. You have to use python 3.x and pip3.
* pip3 install -r requirements.txt --user

**Comment by lgcambero** [comment]
Thank you, you can fix it at last:

apt-get install python3-setuptools
easy_install3 pip
pip3 install -r requirements.txt --user

Good tool!!

**Comment by jteslaxxx** [comment]
First gonna tell that tool is wonderful! Had same problem, made same steps and solved problems! Thanks
